tests/conformance/golang/tcp_ping_identify/mod.rs
`ping_test` fails with older glibc. This PR is not really a fix, just info for a user on the root cause of the error (otherwise the test fails with error about socket connection failure). May be we should compile `ping_test` from sources?
=> Print error if `ping_test` fails to run

src/protocol/request_response/mod.rs
Cancellation handles did not get removed after the request was handled successfully and would instead stay in the cancellation handle hashmap until the node was shut down.
=> protocol/request-response: Fix memory leak

src/protocol/libp2p/kademlia/bucket.rs, src/protocol/libp2p/kademlia/routing_table.rs
Find peers in the routing table close to target using `ClosestBucketsIter` from libp2p.
Resolves https://github.com/altonen/litep2p/issues/38.
=> [kademlia] Use `ClosestBucketsIter` from libp2p to get closest peers

.github/workflows/ci.yml
PR adds additional step to run all jobs from a container. The step is needed because when CI runs from forks repo variables are not accessible. 
cc https://github.com/paritytech/litep2p/pull/64#issuecomment-2011683117
cc https://github.com/paritytech/ci_cd/issues/964
=> [ci] Run ci for PR from forks

src/protocol/mdns.rs
On macOS, failure to use `SO_REUSEPORT` would result in mDNS not being able to bind to the socket, causing `Litep2p::new()` to exit with `EADDRINUSE`.
=> protocol/mdns: Use `SO_REUSEPORT` for the mDNS socket

src/transport/tcp/config.rs, src/transport/tcp/listener.rs, src/transport/tcp/mod.rs, src/transport/websocket/config.rs, src/transport/websocket/listener.rs, src/transport/websocket/mod.rs
Add `reuse_port` option to TCP & WebSocket configs. When set, this both:
1. Sets `SO_REUSEPORT` on sockets.
2. Binds sockets to the listen address port when making outbound connections.
I'm not sure if these two behaviors should be controlled by a single option, but this follows libp2p convention.
CC @altonen
=> Expose `reuse_port` option for TCP and WebSocket transports

CHANGELOG.md, Cargo.lock, Cargo.toml
This PR adds a changelog with:
- prior 0.1 and 0.2 release notes
- release 0.3 notable changes
---
- Expose `reuse_port` option for TCP and WebSocket transports  ([#69](https://github.com/paritytech/litep2p/pull/69))
- protocol/mdns: Use `SO_REUSEPORT` for the mDNS socket  ([#68](https://github.com/paritytech/litep2p/pull/68))
- Add support for protocol/agent version  ([#64](https://github.com/paritytech/litep2p/pull/64))
cc @dmitry-markin please let me know if this makes sense 🙏
=> chore: Release version 0.3.0

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/get_record.rs, src/protocol/libp2p/kademlia/query/mod.rs, src/protocol/libp2p/kademlia/record.rs
This PR exposes the Peer ID that provided the kademlia record
- The `PeerRecord` wrapper is introduced over a kad `Record` and contains the peer that provided the said record
- `GetRecordSuccess` event is extended to provide to the end user the `PeerRecord`
While at it, have extended a test to check that the peer id is propagated through queries 
Created to unblock https://github.com/paritytech/polkadot-sdk/pull/3786
=> kad: Expose the peer that provided the kad record 

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/find_many_nodes.rs, src/protocol/libp2p/kademlia/query/mod.rs, src/protocol/libp2p/kademlia/routing_table.rs
This PR implements the `put_record_to` and `try_put_record_to` to selectively pick peers to update their records.
The main use-case from substrate would be the following:
- A peer is discovered to have an outdated authority record (needs https://github.com/paritytech/litep2p/pull/76)
- Update the record with the latest authority record available (part of this PR)
This PR provided peers to the engine if the peers are part of the kBucket. The first step of the discovery in substrate motivates this assumption. We can probably do things a bit more optimally since we know the peers part of the kBucket were discovered previously (or currently connected):
- The query starts with a [FindNodeContext](https://github.com/paritytech/litep2p/blob/96e827b54f9f937c6d0489bef6a438b48cf50e58/src/protocol/li …
=> kad: Implement put_record_to and try_put_record_to

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/find_many_nodes.rs, src/protocol/libp2p/kademlia/query/mod.rs, src/protocol/libp2p/kademlia/routing_table.rs
This PR implements the `put_record_to` and `try_put_record_to` to selectively pick peers to update their records.
The main use-case from substrate would be the following:
- A peer is discovered to have an outdated authority record (needs https://github.com/paritytech/litep2p/pull/76)
- Update the record with the latest authority record available (part of this PR)
This PR provided peers to the engine if the peers are part of the kBucket. The first step of the discovery in substrate motivates this assumption. We can probably do things a bit more optimally since we know the peers part of the kBucket were discovered previously (or currently connected):
- The query starts with a [FindNodeContext](https://github.com/paritytech/litep2p/blob/96e827b54f9f937c6d0489bef6a438b48cf50e58/src/protocol/li …
=> kad: Implement put_record_to and try_put_record_to (#77)

src/crypto/mod.rs
This PR ensures that litep2p does not panic when decoding public keys from received TCP noise handshake.
The code operated under the assumption that only the `ed25519` key is valid in the context of Substrate.
However, peers could still use a different key (`rsa` / `ecdsa`) and cause the code to panic.
In those cases, an error is returned which terminates the negotiation handshake.
Discovered during testing a sync node with litep2p backend on kusama as part of https://github.com/paritytech/litep2p/pull/83.
```bash
Version: 1.10.0-cd9d08d6311
0: sp_panic_handler::set::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys_common::backtrace::__rust_end_short_backtrace
4: rust_begin_unwind
5: core::panicking::panic_fmt
6: …
```
=> crypto: Don't panic on unsupported key types

.github/workflows/ci.yml
This PR also enabled the CI to run on commits pushed to master.
Modified the running behavior on the PRs, to only limit the CI to branches that are ready to be merged on master.
cc @dmitry-markin
=> ci: Run CI on master and PRs

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs
Small PR to always update the local store on `PutRecordToPeers`.
This is introduced to facilitate the use-case from:
- https://github.com/paritytech/polkadot-sdk/pull/3786/files#diff-5c2ed434b83c3fc3e5b6e2d2bc1895ec870d39e6b77a0f44b3f012694b5a943aR426
Where the `update_local_store` flag is used to optimize kad MemoryStore updates. However, for us this represents a hashmap insert.
While at it, have also filtered out peers that are equal to our local peer ID. 
cc @dmitry-markin
=> kad/store: Set memory-store on an incoming record for PutRecordTo

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/get_record.rs, src/protocol/libp2p/kademlia/query/mod.rs, src/protocol/libp2p/kademlia/record.rs
This PR extends the `GetRecordSucess` variant of kad queries to provide all the query information.
Previously, only the last stored query record was returned to the user.
In the libp2p crate, an event is generated for every found record. However, litep2p responds only when the query finishes.
Records are extended to offer similar information back to the user while sending a minimum number of events.
- A new `RecordsType` is introduced to avoid confusion about records extracted from the local store and records found on the network
- We save the record backed by the most number of peers in our local store
- A panic is removed from the `kad/query` since we now operate with a multitude of records and potentially none
- Expired records are now ignored
=> kad: Expose all peer records of `GET_VALUE` query

src/protocol/libp2p/kademlia/query/find_node.rs, src/protocol/libp2p/kademlia/query/get_record.rs, src/protocol/libp2p/kademlia/query/mod.rs
This PR refactors the FindNode query to make it more robust.
- Avoid panics on unwraps and unimplemented logic
- Separate config immutable variables from main query logic
- Simplifies logic of next_action method
- Private methods for internal logic
It also fixes a bug where only the last peer ID of our results was updated.
- we were registering the first 20 (repl factor) responses
- whenever we got a new response (better) we tried to update just the peerID_ of the last entry
This had a few implications:
- the first 19 entries are never updated with a better (closer) peer
- the distance of the last entry was never updated. And because of this, we might end up in a situation where the record is updated with a furthest distance
```rust
// Presume: 
last_entry: distance = 10, peer = A
// …
```
=> kad: Refactor FindNode query, keep K best results and add tests

CHANGELOG.md, Cargo.lock, Cargo.toml
This is a small patch release that makes the `FindNode` command a bit more robst:
- The `FindNode` command now retains the K (replication factor) best results.
- The `FindNode` command has been updated to handle errors and unexpected states without panicking.
- kad: Refactor FindNode query, keep K best results and add tests  ([#114](https://github.com/paritytech/litep2p/pull/114))
This release introduces breaking changes to the litep2p crate, primarily affecting the `kad` module. Key updates include:
- The `GetRecord` command now exposes all peer records, not just the latest one.
- A new `RecordType` has been introduced to clearly distinguish between locally stored records and those discovered from the network.
Significant refactoring has been done to enhance the efficiency and accuracy …
=> chore: Release v0.5.0

src/protocol/libp2p/ping/mod.rs
We have discovered a race between the TransportService and Protocol interface.
This issue was first seen on the identify protocol:
- https://github.com/paritytech/litep2p/issues/103
After looking a bit closely into it, indeed there might be a chance for the following to happen:
- T0: Transport service sends `TransportEvent::ConnectionEstablished` and `TransportEvent::SubstreamOpened` 
- T1: The peer disconnects
- T2: Ping protocol receives an `TransportEvent::ConnectionEstablished` event for a disconnected peer
- T3: `Ping::on_connection_established` fails to open a substream and `pending_open` is never populated
- T4: Ping protocol receives an `TransportEvent::SubstreamOpened` event which would have panicked litep2p
This PR replaces the `todo!` in case of the race with a warning, and …
=> ping: Make ping fault tolerant wrt outbound substreams races

src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/store.rs, tests/protocol/kademlia.rs
Support manual DHT record insertion to comply with `libp2p` implementation.
=> Support manual DHT record insertion

src/protocol/notification/mod.rs
This PR aims to remove the possible panics from the `protocol/notification` that may happen on missing peer contexts.
=> protocol/notif: Fix panic on missing peer state 

src/transport/common/listener.rs, src/transport/tcp/connection.rs, src/transport/tcp/mod.rs, src/transport/websocket/mod.rs
Move the dns resolving to a dedicated common module and return specific errors on failures. 
Part of: https://github.com/paritytech/litep2p/issues/70
=> transport/common: Share DNS lookups between TCP and WebSocket

CHANGELOG.md, Cargo.lock, Cargo.toml
This release introduces breaking changes into `kad` module. The API has been extended as following:    
- An event `KademliaEvent::IncomingRecord` has been added.    
- New methods `KademliaHandle::store_record()` / `KademliaHandle::try_store_record()` have been introduced.    
This allows implementing manual incoming DHT record validation by configuring `Kademlia` with `IncomingRecordValidationMode::Manual`.    
Also, it is now possible to enable `TCP_NODELAY` on sockets.    
Multiple refactorings to remove the code duplications and improve the implementation robustness have been done.    
- Support manual DHT record insertion ([#135](https://github.com/paritytech/litep2p/pull/135))    
- transport: Make `TCP_NODELAY` configurable ([#146](https://github.com/paritytech/litep2p/pull/146)) …
=> chore: Release v0.6.0

src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/handle.rs, tests/protocol/kademlia.rs
This PR introduces a default TTL for records.
- the default is set to 36h if the record ttl is unspecified
- this ensures the local memory store is not polluted with records without TTL
Part of: https://github.com/paritytech/litep2p/issues/129
=> kad: Set default ttl 36h for kad records

CHANGELOG.md, Cargo.lock, Cargo.toml
This is a bug fixing and security release. curve255190-dalek has been upgraded to v4.1.3, see [dalek-cryptography/curve25519-dalek#659](https://github.com/dalek-cryptography/curve25519-dalek/pull/659) for details.
- kad: Set default ttl 36h for kad records ([#154](https://github.com/paritytech/litep2p/pull/154))
- chore: update ed25519-dalek to v2.1.1 ([#122](https://github.com/paritytech/litep2p/pull/122))
- Bump curve255190-dalek 4.1.2 -> 4.1.3 ([#159](https://github.com/paritytech/litep2p/pull/159))
=> chore: Release v0.6.1

src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/message.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/types.rs, tests/protocol/kademlia.rs
This PR fixes a bug with publisher & expiration time not being preserved in DHT records.
Resolves https://github.com/paritytech/litep2p/issues/129.
=> kademlia: Preserve publisher & expiration time in DHT records

CHANGELOG.md, Cargo.lock, Cargo.toml
This is a bug fixing release. Kademlia now correctly sets and forwards publisher & ttl in the DHT records.
- kademlia: Preserve publisher & expiration time in DHT records ([#162](https://github.com/paritytech/litep2p/pull/162))
=> chore: Release v0.6.2

src/config.rs, src/error.rs, src/lib.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/mdns.rs, src/protocol/notification/tests/mod.rs, src/protocol/request_response/tests.rs, src/transport/manager/limits.rs, src/transport/manager/mod.rs, src/transport/tcp/mod.rs
This PR adds connection limits for: 
- maximum number of inbound established (negotiated) connections
- maximum number of outbound established (negotiated) connections
- any dial attempts are immediately rejected if we reach capacity for the maximum number of outbound established connections
The public API exposes for the connection limits a builder, both on the Litep2pConfig, as well for the limits:
```rust
let litep2p_config = Config::default()
.with_connection_limits(ConnectionLimitsConfig::default()
.max_incoming_connections(Some(3))
.max_outgoing_connections(Some(2)));
```
The connection limits increments and decrements connections identified by their `ConnectionId(usize)`.
Regarding memory consumption, we use 2 hash-maps that require `sizeof(usize) * (num_of_inbound + …
=> transport/manager: Add connection limits for inbound and outbound established connections

src/transport/manager/address.rs, src/transport/manager/mod.rs, src/transport/manager/types.rs
This PR ensures that the transport manager rejects secondary connections.
When the secondary connection is rejected, the internal `dial_record` is preserved.
Added a test to validate this behavior, with multiple wrong endpoints.
Part of: https://github.com/paritytech/litep2p/issues/172
Will keep the issue opened for to further into it. 
=> transport: Reject secondary connections with different connection IDs

src/protocol/libp2p/kademlia/mod.rs
This PR ensures that the records discovered by the `GetRecord` query are not propagated to the memory store.
This makes the litep2p behavior similar to the libp2p.
Another approach could be to put the record into the memory store if the validation mode is `Automatic`. However, for networks with a large number of records, this will exhaust the limit of our memory store.
Thanks @alexggh for catching this 🙏 
Fix for:
- https://github.com/paritytech/litep2p/pull/190
=> kad: Do not update memory store on incoming `GetRecordSuccess`

src/transport/manager/address.rs, src/transport/manager/mod.rs, src/transport/manager/types.rs
This PR fixes an issue where the secondary connection is rejected because it has a different connection ID.
The issue comes from `fn dial_address` which can overwrite the state of a disconnected peer with in-flight dial requests. 
- T0: dial_address 1
- T1: dial_address 2 which overwrites address 1
- T2: dialed address 1 responds with a connection
- T3: connection is rejected
While at it, this PR also:
- removes the need to double lock the peer state (once to read and once to write)
- enforces connection ID checks on dial records in `on_dial_failure`
- adjust the repro case from https://github.com/paritytech/litep2p/pull/176 for the fix
- T0: Dial address A connection ID 1 -> State : Dialing { in-flight-1 }
- T1: Connection is established by remote address C connection ID 3 -> State : …
=> transport: Fix double lock and state overwrite on disconnected peers

.github/workflows/ci.yml, Cargo.toml, src/config.rs, src/crypto/mod.rs, src/crypto/noise/mod.rs, src/crypto/noise/protocol.rs, src/error.rs, src/lib.rs, src/multistream_select/length_delimited.rs, src/protocol/notification/mod.rs, src/protocol/protocol_set.rs, src/substream/mod.rs, src/transport/common/listener.rs, src/transport/manager/handle.rs, src/transport/manager/mod.rs, src/transport/manager/types.rs, src/transport/mod.rs, src/transport/quic/mod.rs, src/transport/tcp/mod.rs, src/yamux/connection/stream.rs, tests/common/mod.rs, tests/conformance/rust/mod.rs, tests/connection/mod.rs, tests/protocol/identify.rs, tests/protocol/notification.rs, tests/protocol/ping.rs, tests/protocol/request_response.rs, tests/substream.rs, tests/webrtc.rs
Put extra transports behind feature flags to make some dependencies optional.
While at it, also made sure no warnings are emitted on the recent rust version.
Resolves https://github.com/paritytech/litep2p/issues/161.
=> Make transports optional

src/transport/quic/mod.rs, src/transport/tcp/mod.rs, src/transport/websocket/mod.rs
Resolves https://github.com/paritytech/litep2p/issues/197.
=> Fix TCP, WebSocket, QUIC leaking connection IDs in `reject()`

src/config.rs, src/lib.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/notification/tests/mod.rs, src/protocol/request_response/tests.rs, src/protocol/transport_service.rs, src/transport/manager/mod.rs, src/transport/mod.rs
Allow configure time duration of keep_alive_timeouts in `TransportService`.
For `RequestResponseProtocol`, use its timeout configuration.
For other protocols, use the original default 5 seconds.
Related issue: #153
=> transport: Allow manual setting of keep-alive timeout

src/protocol/libp2p/kademlia/record.rs, src/protocol/libp2p/kademlia/store.rs, src/protocol/libp2p/kademlia/types.rs
Resolves https://github.com/paritytech/litep2p/issues/195.
=> kad: Add support for provider records to `MemoryStore`

src/crypto/ed25519.rs, src/crypto/mod.rs, src/crypto/noise/mod.rs, src/error.rs, src/lib.rs, src/multistream_select/dialer_select.rs, src/multistream_select/negotiated.rs, src/multistream_select/protocol.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/mod.rs, src/protocol/notification/mod.rs, src/protocol/notification/tests/notification.rs, src/protocol/protocol_set.rs, src/protocol/request_response/mod.rs, src/protocol/request_response/tests.rs, src/transport/common/listener.rs, src/transport/dummy.rs, src/transport/manager/mod.rs, src/transport/mod.rs, src/transport/quic/connection.rs, src/transport/quic/listener.rs, src/transport/quic/mod.rs, src/transport/tcp/connection.rs, src/transport/tcp/mod.rs, src/transport/webrtc/connection.rs, src/transport/webrtc/util.rs, src/transport/websocket/connection.rs, src/transport/websocket/mod.rs, tests/connection/mod.rs
The purpose of this PR is to pave the way for making the Identify protocol more robust, which is currently linked with the low number of peers and connective issues over a long period of time
- https://github.com/paritytech/polkadot-sdk/issues/4925
This PR adds a coherent `DialError` that exposes the minimal information users need to know about dial failures.
- https://github.com/paritytech/polkadot-sdk/issues/5239
A new litep2p event is added for reporting multiple dial errors that occur on different protocols back to the user:
```rust
/// A list of multiple dial failures.
ListDialFailures {
/// List of errors.
///
/// Depending on the transport, the address might be different for each error.
errors: Vec<(Multiaddr, DialError)>,
},
```
This event eases the debugging of substrate …
=> errors: Add `DialError` error and `ListDialFailures` event for better error reporting

src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/message.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/store.rs, src/protocol/libp2p/schema/kademlia.proto
This implements the `ADD_PROVIDER` & `GET_PROVIDER` Kademlia RPC without initiating the queries itself. This should already allow participating in the DHT with content providers and serve all network requests, but won't allow initiating queries (like getting the content provider & starting providing) locally.
Implements "server side" of https://github.com/paritytech/litep2p/issues/201.
- Initiate content provider queries in `litep2p`
- Once the client API for queries is exposed, add conformance tests with `libp2p`
=> kad: Handle `ADD_PROVIDER` & `GET_PROVIDERS` network requests

src/crypto/noise/protocol.rs
This PR ensures that a keypair is only generated for `Curve25519`. This behavior is similar how libp2p creates keypairs. 
=> crypto/noise: Generate keypair only for Curve25519

src/transport/manager/mod.rs
Put test requiring WebSocket transport behind a feature guard.
=> minor: fix tests without `websocket` feature

src/protocol/libp2p/kademlia/query/find_node.rs
This PR introduces a `peer_timeout` to the `FIND_NODE` queries.
- Queries make at most 3 (alpha / parallelism factor) request in parallel
- Introduce a `peer_timeout` after which the pending request doesn't count towards the parallelism factor
This prevents the query from getting stuck when a peer is slow or fails to respond within due time.
The peer can still produce the response at a later time.
Since most queries rely on the same primitives (candidates, pending, responses), we can abstract and adopt a shared wrapper for all queries. This would make the same feature available to the other queries, keeping the code simple and reusing the core functionality. However, that can come at a later time. 
=> find_node: Optimize parallelism factor for slow to respond peers

src/substream/mod.rs
This PR refactors the substream writing to replace the `while remaining { write(byte) }` with the `write_all` method.
- introduce a dedicated function that is shared between substream implementation that handles the varint payload
- replace hardcoded buffer [0; 10] with the encoded buffer of `usize` from the unsigned_varint crate
- flush the identity protocol similar to the varint protocol after successfully writing data
This was driven by the fact that the identity protocol (ie plain bytes without length prefix) uses write_all; and the higher level functions never use that partially written information. I expect the performance improvement to be negligible, however this helps with code maintenance and consistency. 
=> substream: Use write_all instead of manually writing bytes   

src/protocol/libp2p/kademlia/executor.rs
This PR ensures that we save the task `waker` when the executor does not have any pending futures (messages queued to send / receive from the individual substreams).
When the `self.futures` are empty we returned `Poll::Pending`.
However, the given `QueryExecutor::poll_next` would never wake up again.
To mitigate this behavior, save the current waker and notify it upon modifications to `self.futures`.
This was working before because we relied on other tasks to make progress via the `loop { tokio::select! }`. However this ensures that the query executor is efficiently waking up and can work in isolation.
=> query-executor: Save the task waker on empty futures

Cargo.lock, Cargo.toml, src/transport/common/listener.rs
Trust DNS resolver has been rebranded to hickory resolver 
From https://crates.io/crates/trust-dns-resolver:
> NOTICE This project has been rebranded to Hickory DNS and has been moved to the https://github.com/hickory-dns/hickory-dns organization and repo, this crate/binary has been moved to [hickory-resolver](https://crates.io/crates/hickory-resolver), from 0.24 and onward.
=> transport: Replace trust_dns_resolver with hickory_resolver

src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/find_node.rs
This PR makes the substream opening and dialing of query commands more robust.
In the past, the logic of a query action would:
- T0; try to open a substream
- T1; try to dial the peer
There is a race between the moment when a substream is opened and when the peer is dialed (T0 and T1), where the peer could connect to us. The race manifested after extensively running `FindNode` commands via [subp2p-explorer bench-cli](https://github.com/lexnv/subp2p-explorer/tree/main/bench-cli)
To mitigate this race, retry to open the substream on recoverable errors from dialing (ie Error::PeerAlreadyConnected).
=> kad: Fix substream opening and dialing race

src/protocol/libp2p/kademlia/mod.rs, src/protocol/transport_service.rs
Previously `local_peer_id` was declared `pub(crate)` which made it inaccessible to protocols implemented with `UserProtocol`
Implement getter for local peer ID, allowing all protocols having access to `TransportService` to query the local peer ID
=> transport: Implement `TransportService::local_peer_id()`

src/error.rs, src/mock/substream.rs, src/multistream_select/negotiated.rs, src/multistream_select/protocol.rs, src/protocol/connection.rs, src/protocol/libp2p/identify.rs, src/protocol/libp2p/kademlia/executor.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/store.rs, src/protocol/mod.rs, src/protocol/notification/mod.rs, src/protocol/notification/negotiation.rs, src/protocol/notification/tests/notification.rs, src/protocol/notification/tests/substream_validation.rs, src/protocol/protocol_set.rs, src/protocol/request_response/handle.rs, src/protocol/request_response/mod.rs, src/protocol/request_response/tests.rs, src/protocol/transport_service.rs, src/substream/mod.rs, src/transport/manager/handle.rs, src/transport/quic/substream.rs, src/yamux/error.rs, src/yamux/frame/header.rs, src/yamux/frame/io.rs, tests/protocol/request_response.rs, tests/substream.rs
This PR makes several changes to the errors in general, with the main goal of extracting the reject-reason from the request response protocols:
- an `ImmediateDial` error is introduced for failing to dial peers due to internal errors (no addresses available, tried to dial self, already connected etc) to distinguish between network dial failures
- opening substreams now return a `SubstreamError` instead of using the overarching litep2p::Error
- substreams are now implementing `Stream<Error = SubstreamError>` for consistency with opening substreams
- Reject reasons include immediate dialing errors. Ideally, we could expose the same level of information that is exposed via `ListDialErrors` (provide a tuple of addresses with individual dial errors), however that would require a bigger …
=> errors: Introduce immediate dial error and request-response rejection reasons

CHANGELOG.md, Cargo.lock, Cargo.toml, src/protocol/request_response/mod.rs
This release introduces several new features, improvements, and fixes to the litep2p library. Key updates include enhanced error handling, configurable connection limits, and a new API for managing public addresses.
A new `PublicAddresses` API has been added, enabling users to manage the node's public addresses. This API allows developers to add, remove, and retrieve public addresses, which are shared with peers through the Identify protocol.
```rust
// Public addresses are accessible from the main litep2p instance.
let public_addresses = litep2p.public_addresses();
// Add a new public address to the node.
if let Err(err) = public_addresses.add_address(multiaddr) {
eprintln!("Failed to add public address: {:?}", err);
}
// Remove a public address from the node. …
```
=> chore: Release litep2p 0.7.0

src/protocol/request_response/handle.rs, src/protocol/request_response/mod.rs, src/protocol/request_response/tests.rs
This PR refactors the `RequstResponse::run()` method to move away from writing code in `loop { tokio::select! }`.
Instead, the functionality is moved to dedicated functions.
While at it, have remove the `async` from functions that were plain sync and added comments to make the polling a bit clearer.
=> req-resp: Refactor to move functionality to dedicated methods

.github/workflows/ci.yml
PR changes runner for the `test` job in the process of runners unification. More details can be found here https://github.com/paritytech/ci_cd/issues/1039
=> [ci] Change CI runners

src/protocol/libp2p/kademlia/handle.rs, src/protocol/libp2p/kademlia/message.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/query/mod.rs
Implement `ADD_PROVIDER` network request and execute `FIND_NODE` query to publish local provider to the target peers.
Builds upon https://github.com/paritytech/litep2p/pull/200 & https://github.com/paritytech/litep2p/pull/213.
Next PR in the series: https://github.com/paritytech/litep2p/pull/235.
- Make sure unit and integration tests do not reveal issues and merge together with other PRs in the series.
=> kad: Providers part 3: publish provider records (start providing)

src/protocol/libp2p/identify.rs
The identify protocol implementation leaked SubstreamIds and PeerIds via the `pending_opens` hashMap.
Objects were only inserted in the `pending_opens`, however they were never removed.
The only possible purpose of `pending_opens` is to double-check the events coming from the service layer: `TransportEvent::SubstreamOpened`. However this is not needed, as illustrated by the current implementation. 
Part of endeavors to fix memory leaks: https://github.com/paritytech/polkadot-sdk/issues/6149
- custom patched litep2p to dump the internal state of identify protocol running in kusama
=> identify: Fix memory leak of unused `pending_opens`

src/protocol/libp2p/ping/mod.rs
The purpose of the `pending_opens` field is to double check outbound substream opens.
This was used to ensure that the substream ID was indeed opened to a given peer ID.
However, this is not needed considering the `identify` implementation.
Further, the `pending_opens` was leaking `(SubstramId, PeerId)` tuples in cases where the
substream opening would later fail. In other words, the implementation did not remove the tuples on the `TransportEvent::SubstreamOpenFailure` event.
Part of endeavors to fix memory leaks: https://github.com/paritytech/polkadot-sdk/issues/6149
- custom patched litep2p to dump the internal state of identify protocol running in kusama
The code is similar to the identify protocol. However, this leak was more subtle and not of the magnitude of the `identify` protocol …
=> ping: Fix memory leak of unremoved `pending_opens`

src/transport/tcp/mod.rs, src/transport/websocket/mod.rs
The `pending_dials` is populated with a connection ID when initiating outbound connections.
The state is rightfully cleaned up when the dialing fails, and error propagated back to the user.
However, the state was not cleared when the dialing succeeded. This was leading to a subtle memory leak in litep2p.
I used a custom-patched version of litep2p to log the number of pending dials. After a few hours, the pending dials for both TCP and WebSocket connections stabilized at just a few.
```
2024-10-22 17:37:56.252  INFO tokio-runtime-worker litep2p::tcp: status pending_dials=1 pending_inbound_connections=0 pending_connections=1 pending_raw_connections=0 opened_raw=0 cancel_futures=0 pending_open=0
2024-10-22 17:38:26.252  INFO tokio-runtime-worker litep2p::tcp: status pending_dials=0 …
```
=> transport: Fix pending dials memory leak

src/protocol/libp2p/kademlia/executor.rs
This PR adds a `WRITE_TIMEOUT` for sending frames to remote peers.
The `WRITE_TIMEOUT` is set to 15 seconds to mirror the `READ_TIMEOUT`.
Closes: https://github.com/paritytech/litep2p/issues/231
=> kad/executor: Add timeout for writting frames

CHANGELOG.md, Cargo.lock, Cargo.toml
This release adds support for content provider advertisement and discovery to Kademlia protocol implementation (see libp2p [spec](https://github.com/libp2p/specs/blob/master/kad-dht/README.md#content-provider-advertisement-and-discovery)).
Additionally, the release includes several improvements and memory leak fixes to enhance the stability and performance of the litep2p library.
- kad: Providers part 8: unit, e2e, and `libp2p` conformance tests  ([#258](https://github.com/paritytech/litep2p/pull/258))
- kad: Providers part 7: better types and public API, public addresses & known providers  ([#246](https://github.com/paritytech/litep2p/pull/246))
- kad: Providers part 6: stop providing  ([#245](https://github.com/paritytech/litep2p/pull/245))
- kad: Providers part 5: `GET_PROVIDERS` query …
=> chore: Release litep2p version 0.8.0

src/transport/manager/mod.rs
This tiny PR logs when the receiving handlers return none, indicating that they shouldn't be polled further:
- installed protocols
- user commands
- installed transports
=> manager: Log when polling returns Ready(None)

src/transport/manager/mod.rs
This PR ensures that the stream implementation of `TransportContext` does not overflow.
Instead, this PR ensures a round-robin polling strategy with the index capped at the number of elements registered to the `TransportContext`. 
While at it, added a test to ensure polling functionality works with round-robin expectations. 
Discovered during: https://github.com/paritytech/litep2p/issues/282
=> manager: Avoid overflow on stream implementation for `TransportContext`

src/transport/tcp/mod.rs, src/transport/websocket/mod.rs
This PR handles the following:
- Align Webscoket listener with TCP listener to not miss out on `Poll::Ready(None)` events and enhance logging
- Add warnings whenever pending connection IDs do not exist
- ~~Filtering out `Poll::Ready` events into `Poll::Pending` without calling the context waker will result in the scheduler not polling in the future. This was happening, for example, for both TCP and Websocket when receiving a connection established event that was previously canceled~~
Discovered during: https://github.com/paritytech/litep2p/issues/282
=> transports: Fix missing Poll::Ready(None) event from listenener

src/lib.rs, src/protocol/libp2p/kademlia/executor.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/store.rs, src/transport/tcp/mod.rs, src/transport/websocket/mod.rs, src/utils/futures_stream.rs, src/utils/mod.rs
This PR ensures that the transport (TCP / WebSocket) implementation wakes up the waker `FuturesUnordered` on adding futures to the set.
This is one of the async rough edges in Rust, to properly illustrate the issue I've compiled this rust example (comment and uncomment like 43 to see the issue in action):
The future is not polled again: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1e801c4864599c54a98bb9f30be1fdd5
The future is delayed (from 2s to 3s) because it relies on some other implementation to wake up the context waker:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=951080892763ca7d02ae9c5617da6c5d
The `poll_next` implementation polls 3 objects:
- `listener`: accepts incoming socket connections
- `pending_raw_connections`: dialing …
=> transport: Fix waking up on filtered events from `poll_next` 

src/transport/manager/limits.rs, src/transport/manager/mod.rs
This PR ensures that connection IDs are properly tracked to enforce connection limits.
After ~1/2 days the substrate litep2p running node is starting to reject multiple pending socket connections.
This is related to the fact that accepting of established connection is a two-part process:
- step 1. Can we accept the connection based on number of connections?
- step 2. The transport manager transitions the peer state
- step 3. If the transition succeeds, the connection is tracked (inserted in a hashmap).
If step 2 fails, we were previously leaking the connection ID. The connection ID is also counting towards the maximum number of connections the node can sustain.
This PR effectively modifies the connection limits API, `on_connection_established` is split into two methods:
- …
=> manager: Fix connection limits tracking of rejected connections 

CHANGELOG.md, Cargo.lock, Cargo.toml
This release includes key fixes that enhance the stability and performance of the litep2p library, focusing on long-running stability and improvements to polling mechanisms.
This issue caused long-running nodes to reject all incoming connections, impacting overall stability.
Addressed a bug in the connection limits functionality that incorrectly tracked connections due for rejection.
This issue caused an artificial increase in inbound peers, which were not being properly removed from the connection limit count.
This fix ensures more accurate tracking and management of peer connections [#286](https://github.com/paritytech/litep2p/pull/286).
This release provides multiple fixes to the polling mechanism, improving how connections and events are processed:
- Resolved an overflow issue in …
=> chore: Release litep2p version 0.8.1

src/protocol/request_response/mod.rs, src/protocol/request_response/tests.rs
When a new connection is reported to the request-response protocol, the protocol tracks the state of the connection if and only if it could open a substream with the remote peer.
We do not track the state of the connection in cases where the substream cannot be opened because the connection is closed.
A further `ConnectionClosed` event triggered a debug_assert assumption for this case. The assumption is wrong since opening substreams can fail which informs us that the connection is closed.
Connection details not tracked:
https://github.com/paritytech/litep2p/blob/eed0f755d591eb49e1b715a78aceb5a653ddf529/src/protocol/request_response/mod.rs#L267-L284
Which later leads to panics:
https://github.com/paritytech/litep2p/blob/d6fae559fbe2aaf8cb3fff021fb5608ca7b43766/src/protocol/request_response …
=> req-resp: Fix panic on connection closed for substream open failure

src/protocol/transport_service.rs
Tiny PR to provide fewer details for trace logs of the transport service components.
During testing of Kusama litep2p on local nodes, I noticed that the information provided by the `last_activity` is excessive. This is a dump of all connected peers with a timestamp, and for 1k inbound and 1k outbound peers provides too much information.
=> transport_service/logs: Provide less details for trace logs

CHANGELOG.md, Cargo.lock, Cargo.toml
This release ensures that the provided peer identity is verified at the crypto/noise protocol level, enhancing security and preventing potential misuses.
The release also includes a fix that caused `TransportService` component to panic on debug builds.
- req-resp: Fix panic on connection closed for substream open failure  ([#291](https://github.com/paritytech/litep2p/pull/291))
- crypto/noise: Verify crypto/noise signature payload  ([#278](https://github.com/paritytech/litep2p/pull/278))
- transport_service/logs: Provide less details for trace logs  ([#292](https://github.com/paritytech/litep2p/pull/292))
=> chore: Release version 0.8.2

src/protocol/request_response/mod.rs
Similar to https://github.com/paritytech/litep2p/pull/296, there is a possibility of leaking memory in the following edge-case:
- T0: Connection is established and outbound substream is initiated with peer
- This maps the substream ID to the request bytes information
- T1: Connection is closed before the service has a chance to report `TransportEvent::SubstreamOpened` or `TransportEvent::SubstreamOpenFailure`
In this case, if we connect and immediately disconnect with a request in flight, we are effectively leaking the request bytes.
Detected by:
- https://github.com/paritytech/litep2p/pull/294
- We are leaking ~111 requests over 3 days timespan:
=> req-resp: Fix memory leak of pending substreams

src/protocol/notification/mod.rs
This PR fixes a subtle memory leak that can happen in the following edge-case situation:
- connection is established and substream outbound is initiated with remote peer
- the substream ID is tracked until the substream either completes successfully or fails
- the connection is closed soon after, leading to no substream events ever being generated
For this edge-cases, we need to remove the tracking of the substream ID when the connection is reported as closed.
This has been detected after running a node for more than 2 days with the following generic metrics PR:
- https://github.com/paritytech/litep2p/pull/294
Closes: https://github.com/paritytech/litep2p/issues/295
=> notification: Fix memory leak of pending substreams

CHANGELOG.md, Cargo.lock, Cargo.toml
This release includes two fixes for small memory leaks on edge-cases in the notification and request-response protocols.
- req-resp: Fix memory leak of pending substreams  ([#297](https://github.com/paritytech/litep2p/pull/297))
- notification: Fix memory leak of pending substreams ([#296](https://github.com/paritytech/litep2p/pull/296))
=> chore: Release version 0.8.3

Cargo.lock, Cargo.toml
Update hickory resolver to latest release version to avoid the following security incident:
- https://rustsec.org/advisories/RUSTSEC-2024-0421.html
The incident is not impacting substrate based chains, because we use `crypto/noise` on top of connections. Therefore, malicious nodes cannot impersonate other peerIDs.
=> chore: Update hickory-resolver to version 0.24.2

src/protocol/libp2p/identify.rs, src/utils/futures_stream.rs
This PR replaces the identify `FuturesUnordered` with `FuturesStream`. This effectively fixes delays in processing outbound events.
- ensure that identify warns if the transport service is closed (produces no events).
- identify no longer exits on pending outbound events
Related to:
- https://github.com/paritytech/litep2p/pull/287
- https://github.com/paritytech/litep2p/issues/300
=> identify: Replace FuturesUnordered with FuturesStream

src/protocol/mdns.rs
This PR ensures that when MDNS encounters an error it does not terminate other litep2p components.
Previously, if MDNS failed to send a query or to handle the incoming packets it would exit.
The exit is presented by the following log line observed on kusama validator:
```
tokio-runtime-worker litep2p::mdns: failed to send mdns query error=IoError(NetworkUnreachable)
```
This situation is causing the substrate Discovery mechanism to also exit, which propagates to the litep2p kademlia handler that exits as well. This leaves the node unable to discover the network or handle incoming substreams.
The issue was reproduced locally with a tokio interval patch that exits the MDNS component after having connectivity in Kusama:
```
2024-12-11 12:50:34.425 ERROR tokio-runtime-worker litep2p::mdns: …
```
=> mdns/fix: Failed to register opened substream

CHANGELOG.md, Cargo.lock, Cargo.toml
This release aims to make the MDNS component more robust by fixing a bug that caused the MDNS service to fail to register opened substreams. Additionally, the release includes several improvements to the `identify` protocol, replacing `FuturesUnordered` with `FuturesStream` for better performance.
- mdns/fix: Failed to register opened substream  ([#301](https://github.com/paritytech/litep2p/pull/301))
- identify: Replace FuturesUnordered with FuturesStream  ([#302](https://github.com/paritytech/litep2p/pull/302))
- chore: Update hickory-resolver to version 0.24.2  ([#304](https://github.com/paritytech/litep2p/pull/304))
- ci: Ensure cargo-machete is working with rust version from CI  ([#303](https://github.com/paritytech/litep2p/pull/303))
=> chore: Release litep2p v0.8.4

CHANGELOG.md, Cargo.lock, Cargo.toml
This release provides partial results to speed up `GetRecord` queries in the Kademlia protocol.
- kad: Provide partial results to speedup `GetRecord` queries  ([#315](https://github.com/paritytech/litep2p/pull/315))
=> chore: Release litep2p version 0.9.0

src/multistream_select/dialer_select.rs, src/multistream_select/negotiated.rs
This PR backports https://github.com/libp2p/rust-libp2p/pull/4019/files, effectively ensuring that our `poll_close` flushes any data immediately without waiting for negotiation to complete.
Closes an outdated PR: https://github.com/paritytech/litep2p/pull/62
=> multistream: Do not wait for negotiation in poll_close

src/multistream_select/dialer_select.rs, src/multistream_select/listener_select.rs, src/multistream_select/mod.rs, src/multistream_select/protocol.rs, src/transport/webrtc/connection.rs
This PR brings parity between the litep2p mutlistream-select implementation and the libp2p one.
There was a mismatch in the litep2p implementation which resulted in decoding empty bytes into `Message::Protocols([ ])`. In contrast, libp2p returns an `io::error` since the message is invalid.
While at it have added a few tests to ensure our implementation works as expected
=> multistream-select: Enforce `io::error` instead of empty protocols

src/protocol/request_response/mod.rs, src/protocol/request_response/tests.rs, src/utils/futures_stream.rs
This PR replaces the in-house built `SubstreamSet` with the `FuturesStream`.
- provide fairness for substreams that produce elements based on the `FuturesUnordered` implementation
- clone free implementation for peerId and requested
- substream object is readily available once the substream produces a request (ie there's no need to pay for the hashmap element retrieval)
Substreams are no longer removed from the `FuturesStream` and instead they are left to expire with the `ConnectionClosed` event. This has the side-effect of emitting a `debug` log and it simplifies state tracking.
=> req-resp: Replace SubstreamSet with FuturesStream

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/protocol/libp2p/kademlia/routing_table.rs, src/protocol/libp2p/kademlia/types.rs
This PR brings up to date the following crates, which include no breaking changes or minimal changes:
| Crate | Before | After
-| - | - 
| indexmap | 2.0.0 | 2.7.1
| mocall  | 0.13.0 | 0.13.1
| simple-dns | 0.7.0 | 0.9.3
socket2 | 0.5.7 | 0.5.8
thiserror | 1.0.61 | 2.0.11
unit | 0.9.5 | 0.10.0
x25519-dalek | 2.0.0 | 2.0.1
x509-parser | 0.16.0 | 0.17.0
=> cargo: Bring up to date multiple dependencies

src/transport/websocket/stream.rs
This PR avoids an allocation by clearing out the write buffer elements.
While at it, have increased the buffer size from 2000 to 8192 for extra space and cache alignment. This is the default value used by std/tokio implementation for buffered operations.
=> websocket/stream: Avoid memory allocations on flushing

Cargo.lock, Cargo.toml, src/transport/websocket/stream.rs
This PR updates the following dependencies:
- tokio tungstenite
- URL crate to facilitate the new tungstenite version
The tokio tungstenite update changed the API of webscoket messages, which motivated the following changes:
- When`poll_ready` or `poll_flush` returned `Poll::Pending`, the websocket state would forever remain poisoned. 
- This has the side effect of returning `UnexpectedEof` on consecutive calls, which led to the connection being terminated
- The state machine of the websocket is simplified to just 3 states
- Writer buffer and pointer are merged under one BytesMut instance
- `poll_read` implementation is simplified as well to make the code more readable
=> websocket/stream: Fix unexpected EOF on `Poll::Pending` state poisoning 

src/protocol/libp2p/kademlia/bucket.rs, src/protocol/libp2p/kademlia/routing_table.rs
closes https://github.com/paritytech/litep2p/issues/53
=> Clone only needed KademliaPeers when yielding closest nodes

src/transport/websocket/stream.rs
This PR tests the following scenarios for the websocket stream implementation: 
- Test reading from internal buffers without touching the streams
- Test poll pending during reads
- Test poisoned state
- Ping pong between server and client
- Test closing the stream
- Test write and flush
- Test flushing on empty buffer
- Test write to internal buffers
=> websocket/stream/tests: Add tests for the stream implementation

src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/mod.rs
This PR sets the default kademlia message to 70 KiB
The limit can be configurable using the config builder API.
=> kad: Set upper limits for kademlia messages 

CHANGELOG.md, Cargo.lock, Cargo.toml
This release introduces an API for setting the maximum kademlia message size.
- kad: Set upper limits for kademlia messages  ([#357](https://github.com/paritytech/litep2p/pull/357))
=> chore: Release litep2p v0.9.3

Cargo.toml, src/multistream_select/dialer_select.rs
The following crates are made optional, depending on the Quic feature flag:
- ring
- rustls
This effectively ensures that litep2p is not leaking outdated dependencies for experimental features (ie quic).
Closes: https://github.com/paritytech/litep2p/issues/330
=> features: Move quic related dependencies under feature flag

src/codec/identity.rs
This PR adds a tiny check to ensure smaller payloads than declared to the identify codec return None.
=> codec: Decode smaller payloads for identity to None

src/protocol/notification/mod.rs, src/protocol/notification/tests/notification.rs
This PR ensures that notification tasks are fully terminated when the associated handle is dropped, addressing an issue specific to `minimal-relay-chains`. We have operated from the assumption that the handle is never supposed to get dropped, since protocols cannot be dynamically injected after the backend is started.
This PR effectively reduces the CPU usage of minimal-relay-chains from 7% to 0.1%.
We have noticed that the CPU consumption of minimal-relay-chains has increased compared to libp2p backends. However, our metrics for CPU consumption of full relay chains have drastically improved.
The issue is the following:
- substrate needs a block-announces notification config to initiate the network components.
- the minimal-relay-chains do not need this notification around, and drop the …
=> notifications: Exit protocols on handle drop to save up CPU of `minimal-relay-chains`

src/transport/websocket/connection.rs, src/transport/websocket/stream.rs, tests/connection/mod.rs, tests/protocol/request_response.rs
This PR addresses a bug in the WebSocket stream state machine. The internal state was incorrectly reset to `State::ReadyToSend` upon receiving `Poll::Pending`. The correct behavior is to retain the `State::FlushPending` state until the flush operation completes.
Additionally, the following tests were backported from the TCP connection component:
- yamux_timeout_listener
- yamux_timeout_dialer
- yamux_not_supported_listener
- yamux_not_supported_dialer
- noise_timeout_dialer
- noise_wrong_handshake_listener
- noise_timeout_listener
- noise_not_supported_listener
- noise_not_supported_dialer
- multistream_select_not_supported_listener
- multistream_select_not_supported_dialer
While at it, we had a test guarded by a wrongly named feature flag `webscocket`, which is now also enabled.
cc …
=> websocket/stream: Fix state reset and backport connection tests

src/crypto/noise/mod.rs, src/transport/tcp/connection.rs, src/transport/websocket/connection.rs, src/transport/websocket/mod.rs, src/transport/websocket/stream.rs, tests/connection/mod.rs, tests/protocol/request_response.rs
This PR sets timeout limits for the crypto/noise handshake negotiation.
By default, the timeout is bounded similar to protocol negotiation to the substream open timeout.
To allow this change, the WebSocket internal API has been opened to accept the open timeout. Before this change, we had no granular control and used the connection timeout as a fallback.
=> crypto/noise: Set timeout limits for the noise handshake

src/protocol/libp2p/identify.rs
This PR improves the decoding of the identify messages by checking the following:
- if provided, the public key must decode properly and point towards the same peer ID
- on failure the identify message is not propagated to the higher levels
- empty addresses or addresses corresponding to different peers are removed from the message
- added extra debug logs to the identify component
- discovered the whole network of polkadot and kusama using https://github.com/lexnv/subp2p-explorer
- all the provided identify messages decoded correctly (including all addresses and pKs)
=> identify: Improve identify message decoding

CHANGELOG.md, Cargo.lock, Cargo.toml, src/protocol/libp2p/identify.rs
This release brings several improvements and fixes to litep2p, advancing its stability and readiness for production use.
This release addresses an issue where notification protocols failed to exit on handle drop, lowering CPU usage in scenarios like minimal-relay-chains from 7% to 0.1%.
- Kademlia:
- Optimized address store by sorting addresses based on dialing score, bounding memory consumption and improving efficiency.
- Limited `FIND_NODE` responses to the replication factor, reducing data stored in the routing table.
- Address store improvements enhance robustness against routing table alterations.
- Identify Codec:
- Enhanced message decoding to manage malformed or unexpected messages gracefully.
- Bitswap:
- Introduced a write timeout for sending frames, preventing protocol hangs or …
=> chore: Release litep2p v0.9.4

src/substream/mod.rs, tests/protocol/notification.rs
This PR ensures that zero-length frames are propagated to higher levels.
An issue was noted with the compatibility between litep2p and smoldot, which resulted in smoldot not being accepted by substrate-based chains.
The issue stems from the litep2p substream (high level) implementation, which did not handle zero-length frames.
Smoldot sends during the notification handshake a zero-length frame (ie, `frame [0]`).
However, full nodes (litep2p and libp2p) send the node role `Role::Full` (ie, `frame [1, 1]`).
Substrate nodes expected the node `Role`, however zero-length frames were never punished.
This behavior causes the zero-length frames to go unnoticed and further call into `poll_read`.
In the case of smoldot, the connection is terminated after the handshake timeout of 10 seconds.
- …
=> substream/fix: Allow empty payloads with 0-length frame

src/codec/identity.rs, src/crypto/noise/mod.rs, src/protocol/libp2p/kademlia/bucket.rs, src/transport/tcp/connection.rs, src/transport/websocket/connection.rs, tests/conformance/rust/kademlia.rs
This PR enriches the errors coming from the crypto/noise decryption by providing peer IDs.
This is useful for debugging:
- https://github.com/paritytech/polkadot-sdk/issues/8525
=> crypto/noise: Show peerIDs that fail to decode

CHANGELOG.md, Cargo.lock, Cargo.toml
This release primarily focuses on strengthening the stability of the websocket transport. We've resolved an issue where higher-level buffering was causing the Noise protocol to fail when decoding messages.
We've also significantly improved connectivity between litep2p and Smoldot (the Substrate-based light client). Empty frames are now handled correctly, preventing handshake timeouts and ensuring smoother communication.
Finally, we've carried out several dependency updates to keep the library current with the latest versions of its underlying components.
- substream/fix: Allow empty payloads with 0-length frame  ([#395](https://github.com/paritytech/litep2p/pull/395))
- websocket: Fix connection stability on decrypt messages  ([#393](https://github.com/paritytech/litep2p/pull/393))
- …
=> chore: Release litep2p version 0.9.5

src/protocol/notification/mod.rs, src/protocol/transport_service.rs, src/transport/manager/handle.rs, src/transport/manager/mod.rs
Part of the investigation from:
- https://github.com/paritytech/polkadot-sdk/issues/8474
=> notification: Unregister dropped protocols

src/crypto/noise/mod.rs, src/protocol/libp2p/kademlia/config.rs, src/protocol/libp2p/kademlia/mod.rs, src/protocol/libp2p/kademlia/store.rs
Allow changing Kademlia memory store defaults.
Required for https://github.com/paritytech/litep2p/issues/405.
=> kad: Expose memory store configuration

Cargo.lock, Cargo.toml
This PR updates the tokio tunstenite (the crate we use for websocket connections) to the latest version.
I expect this not to improve things considerably for:
- https://github.com/paritytech/polkadot-sdk/issues/9169
=> cargo: Update tokio-tungstenite to 0.27.0
